apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: gateway
    {{- include "kindling-snapshot.labels" . | nindent 4 }}
spec:
  selector:
    app: gateway
  ports:
  - port: {{ .Values.gateway.port }}
    targetPort: {{ .Values.gateway.port }}
    protocol: TCP
