apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: gateway
    {{- include "kindling-snapshot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: {{ .Values.gateway.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.gateway.port }}
        env:
        - name: ORDERS_URL
          value: "http://{{ .Release.Name }}-orders:5000"
        - name: INVENTORY_URL
          value: "http://{{ .Release.Name }}-inventory:3000"
