apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory
  labels:
    app: inventory
    {{- include "kindling-snapshot.labels" . | nindent 4 }}
spec:
  selector:
    app: inventory
  ports:
  - port: {{ .Values.inventory.port }}
    targetPort: {{ .Values.inventory.port }}
    protocol: TCP
