apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-new-service
  labels:
    app: new-service
    {{- include "kindling-snapshot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.new_service.replicas }}
  selector:
    matchLabels:
      app: new-service
  template:
    metadata:
      labels:
        app: new-service
    spec:
      containers:
      - name: new-service
        image: {{ .Values.new_service.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.new_service.port }}
        env:
        {{- if .Values.new_service.env.REDIS_URL }}
        - name: REDIS_URL
          value: {{ .Values.new_service.env.REDIS_URL | quote }}
        {{- end }}
        {{- if .Values.new_service.env.MONGO_URL }}
        - name: MONGO_URL
          value: {{ .Values.new_service.env.MONGO_URL | quote }}
        {{- end }}
