apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifications
  labels:
    app: notifications
    {{- include "kindling-snapshot.labels" . | nindent 4 }}
spec:
  selector:
    app: notifications
  ports:
  - port: {{ .Values.notifications.port }}
    targetPort: {{ .Values.notifications.port }}
    protocol: TCP
