apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orders
  labels:
    app: orders
    {{- include "kindling-snapshot.labels" . | nindent 4 }}
spec:
  selector:
    app: orders
  ports:
  - port: {{ .Values.orders.port }}
    targetPort: {{ .Values.orders.port }}
    protocol: TCP
